### ISSUE TITLE
get_value() method is deprecated and removed

### ISSUE THREAD

**Issue by jwparks** [ContextLab/quail#120]
Thank you for great software.

I found some trivial errors when using quail package.

in the function `quail.analysis.recmat._similarity_smooth`, 
`.get_values()` method is removed in pandas now.

below is the list of lines which make trivial errors
```
lists = presented.index.get_values()
p = np.vstack(p_list.apply(get_feature).get_values())
r = r_list.dropna().apply(get_feature).get_values()
```
I tried to replace it by `to_numpy()` then anyway it works.

**Comment by jeremymanning** [comment]
thanks @jwparks -- this is fixed in the latest updated!
