### ISSUE TITLE
feature request: data loading functions

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/quail#29]
We should substantially fill out our data loading capabilities to support a range of data formats.  We should also provide good documentation for writing parsers for arbitrary data formats.

These will be critical for convincing others to use our tools-- if they can't easily use them with their own datasets, they won't care about pyrec.

The best way to get a sense of which formats we'll want to support may be to talk to other labs...but at the very least we should discuss.

**Comment by andrewheusser** [comment]
we have a load function for our EL experiments now. Here's an example of how to use it:

```
dbpath = ['/Users/andyheusser/Documents/github/FRFR-analyses/data/encoding/participants-room1-041717.db',
          '/Users/andyheusser/Documents/github/FRFR-analyses/data/encoding/participants-test-room2.db']
recpath = '/Users/andyheusser/Documents/github/FRFR-analyses/data/recall/'
remove_subs = ['debugCWO54U:debugQ59MF8', 'debugE1CAO3:debugONZ2R5', 'debugXG82XV:debug7XPXQA']
wordpool = '/Users/andyheusser/Documents/github/FRFR-analyses/stimuli/cut_wordpool.csv'
experiments = ['0.0', '1.0', '1.1', '2.1', '3.2', '4.1', '5.1', '6.1', '7.1', '8.1']

# create a list of eggs, where each egg is a different experiment
groupby = {'exp_version': [['0.0','1.0','1.1'], '2.1', '3.2', '4.1', '5.1', '6.1', '7.1', '8.1']}
eggs = quail.load(dbpath=dbpath, recpath=recpath, remove_subs=remove_subs,
                  wordpool=wordpool, experiments=experiments, groupby=groupby)
```

**Comment by andrewheusser** [comment]
where `eggs` is a list of `egg` objects the length of `groupby`
