### ISSUE TITLE
weekly reports: simplifying syntax

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/quail#32]
there's a lot of repeated/copied code-- e.g. copying the same command for experiments 1 -- 6.  instead, these should be written as loops.  we can specify a list of labels to go with each experiment number, and then each command should loop through that list to create the plots.

**Comment by andrewheusser** [comment]
this is a couple different issues, some of which are implemented, so im going to close this and reopen new issues with whats left.  

-`Analyze` can now take lists of eggs and lists of analyses and return lists (or nested lists). 
-`Plot` can take a list of analyzed_data, and plot it  

What's left is:

-`Plot` handling lists of key word args (which will require some refactoring)
- `Plot` handling nested lists
