### ISSUE TITLE
enhancement: tufte plot styling

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/quail#41]
we could use tufte-style slope plots (SPC, PFR, PNR, Lag-CRP) and bar plots (fingerprints) to beautify out plot styles

inspiration: https://github.com/juanshishido/tufte

**Comment by jeremymanning** [comment]
also: https://github.com/pascal-schetelat/Slope

**Comment by andrewheusser** [comment]
seaborn has a `ticks` style that is pretty clean:

![image](https://cloud.githubusercontent.com/assets/6596567/25412205/3e3110f6-29ef-11e7-921c-f7ad7acd9a56.png)

we could start with that and add a layer of our own defaults (if we want thinner lines, bars, etc). I also like the blue background:

![image](https://cloud.githubusercontent.com/assets/6596567/25412289/b069cc12-29ef-11e7-89cf-6816aebf0ead.png)

**Comment by andrewheusser** [comment]
@jeremymanning any preferences on the plot styles? Personally I like the way they are now

**Comment by jeremymanning** [comment]
yeah, i like them too-- let's stick with this style

**Comment by andrewheusser** [comment]
👍 cool

**Comment by jeremymanning** [comment]
actually-- now that you've closed this, one more comment: we should make sure the plots are consistent with each other (e.g. default colormaps, axis grids, font sizes, etc.).  i think we're good but we should pay attention to this.

**Comment by jeremymanning** [comment]
(feel free to close if we're already being consistent-- but i noticed that the example bar plots don't have axis grids, whereas the lag-CRPs and SPCs do)

**Comment by andrewheusser** [comment]
I think all styles are consistent across the plots. Which example bar plot are you referring to?

**Comment by jeremymanning** [comment]
the one in this thread (see above)...maybe that was an old example?

**Comment by jeremymanning** [comment]
nvm-- i think we're good.  closing.

**Comment by andrewheusser** [comment]
ah, that was a alternative style option 🎉 👍
