### ISSUE TITLE
decode_speech function

### ISSUE THREAD

**Issue by andrewheusser** [ContextLab/quail#42]
this function would take a file or folder of audio files of free recall data and return the decoded results.

example:

`rec_data = quail.decode_speech('/path/to/file.flac')`

where rec_data is a list of words and

`rec_data = quail.decode_speech(folder='/path/to/folder')`

where rec_data is a list of lists of words.

**Comment by jeremymanning** [comment]
this function looks great to me as described.  one tricky piece is that we'll need to also include instructions for getting the user's Google Cloud API account set up and adding credentials to their local file.  also, we should add a template credentials file to the repository and then make sure that our own (lab) credentials are not accidentally shared with the world.
