### ISSUE TITLE
neural features

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/quail#54]
for neuroimaging experiments, automatically extract neural features (power spectra, brain maps, etc.) and include these in each presentation/recall stimulus feature set.

other things to think about/implement:
- infer the types of features from the data type
- allow the user to pass in a feature extraction function to convert brain data to feature vectors

**Comment by andrewheusser** [comment]
this type of analysis can be done with the new naturalistic features. good to close @jeremymanning ?

**Comment by jeremymanning** [comment]
Yep, closing
