### ISSUE TITLE
JOSS: Who is Campbell E. Field?

### ISSUE THREAD

**Issue by RichardLitt** [ContextLab/quail#72]
In the [paper.md](paper/paper.md) file, there is this listing:

```
 - name: Campbell E. Field
   orcid: 0000-0001-7260-635X
   affiliation: 1
```

Campbell does not seem to be a contributor of code to this repo. I am curious why that name was included in the paper. Related to https://github.com/openjournals/joss-reviews/issues/424.

**Comment by jeremymanning** [comment]
@RichardLitt Campbell is one of the researchers who helped to test the software and collect experimental data that we've been using to test the toolbox.

The author roles were:
- Andrew Heusser: lead developer (code + design)
- Paxton Fitzpatrick, Campbell Field, and Kirsten Ziman: each contributed code and/or ideas and/or data
- Jeremy Manning: code, ideas, and overall design guidance

**Comment by RichardLitt** [comment]
Great. Just checking, then. Thank you!
