### ISSUE TITLE
JOSS: Update submission version

### ISSUE THREAD

**Issue by RichardLitt** [ContextLab/quail#73]
Update the submission version for JOSS from v0.1.0 to v0.1.3, to match current releases. 

Related to https://github.com/openjournals/joss-reviews/issues/424.

**Comment by jeremymanning** [comment]
done.

**Comment by jeremymanning** [comment]
@andrewheusser can you tag the new version (0.1.4) and update [this file](https://github.com/ContextLab/quail/blob/master/paper/codemeta.json) once everything else is good to go with the submission (I think we've now dealt with everything-- @RichardLitt can you confim?).  That way the version of the software in the paper and on pip will include these latest changes to the documentation.

**Comment by jeremymanning** [comment]
(Also please push 0.1.4 to pip once it's tagged.)

**Comment by andrewheusser** [comment]
Ok, the version is updated and on pip: https://pypi.python.org/pypi/quail/0.1.4

**Comment by jeremymanning** [comment]
🎉  awesome!  closing this issue...
