### ISSUE TITLE
Improve try it section - unable to launch binder or use Jupyter repo

### ISSUE THREAD

**Issue by RichardLitt** [ContextLab/quail#75]
Clicking on the binder link in the README led to http://mybinder.org/repo/contextlab/quail-example-notebooks, which presented a never-ending loading image. I am not sure that this is working as expected. 

Likewise, going to the Jupyter repository was not useful. I don't know how to run Jupyter, or I am missing context on how to use that repository. 

Part of https://github.com/openjournals/joss-reviews/issues/424.

**Comment by jeremymanning** [comment]
Hi @RichardLitt, the binder server is down indefinitely, so we will remove that link in our readme file.

Here's a Jupyter tutorial: [[link](https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/)].  I'll add some documentation to that repository.

**Comment by RichardLitt** [comment]
Sounds good to me. Feel free to close when the README is updated.

**Comment by RichardLitt** [comment]
Once this and #76 is landed, I think that's it for the JOSS review.

**Comment by andrewheusser** [comment]
@RichardLitt i commented out the binder link (I plan to uncomment it when binder is back online) and updated the `quail-example-notebooks` repo with instructions on how to get the notebooks running: https://github.com/ContextLab/quail-example-notebooks
