### ISSUE TITLE
Unable to run example from README

### ISSUE THREAD

**Issue by RichardLitt** [ContextLab/quail#76]
The example in the README errored. 

```
import quail

# presented words
presented_words = [['cat', 'bat', 'hat', 'goat'],['zoo', 'animal', 'zebra', 'horse']]

# recalled words
recalled_words = [['bat', 'cat', 'goat', 'hat'],['animal', 'horse', 'zoo']]

# create egg
egg = quail.Egg(pres=presented_words, rec=recalled_words)

#load data
egg = quail.load_example_data()

#analysis
analyzed_data = quail.analyze(egg, analysis='accuracy', listgroup=['average']*16)
```

I also tried with the second `egg` commented out. Should an argument be passed to `load_example_data()`? Would it be possible to provide an egg in the example which could be used to generate graphs as in the examples? Am I missing something? 

Discovered as part of https://github.com/openjournals/joss-reviews/issues/424.

**Comment by paxtonfitzpatrick** [comment]
@RichardLitt should be fixed now

**Comment by RichardLitt** [comment]
Thank you. I am now able to run it. 

The graph that appears is different in style from what is in the README. Is this expected? 

![figure_1](https://user-images.githubusercontent.com/910753/31205552-0f6388fa-a940-11e7-92f6-736e7831eaa9.png)

**Comment by paxtonfitzpatrick** [comment]
Yes, that's expected for now.  I'll update the graphs that appear in the README to match the output shortly

**Comment by andrewheusser** [comment]
@RichardLitt the figures are now updated to reflect the output of the README code (e5c441547faed527b054522271e7029ef4470c94)

cc: @paxtonfitzpatrick

**Comment by RichardLitt** [comment]
The new figures don't look the same as the one I posted above - no background, for instance. Do you have special settings for your output graphs?

**Comment by andrewheusser** [comment]
Ah! No, I think it stems from the fact that `seaborn`, a package that we rely on for plotting, updated their default figure styles.  I have an older version and you must have the newest.  I'll update the figures to reflect the latest version of seaborn.

**Comment by andrewheusser** [comment]
ok! figures are updated :)
