### ISSUE TITLE
documentation: Not all methods listed in readthedocs API documentation

### ISSUE THREAD

**Issue by RichardLitt** [ContextLab/quail#77]
For instance, `load.load_example_data` is not listed. Is there a reason only some methods are listed? That's the only one I could see in __init__.py which is relevant; of course, there are private methods in the python files which aren't exported.

On a related note, in the README Contributing section, it is specified that all public methods should be documented in the README. However, that is not where the documentation lives - it lives in docs, on readthedocs. Perhaps change the Contributing section? 

I may be missing something here! Apologies if so. Part of https://github.com/openjournals/joss-reviews/issues/424.

**Comment by andrewheusser** [comment]
@RichardLitt `quail.load_example_data` now has a docstring and is documented on readthedocs.  Also updated the README contribute section to point to the readthedocs instead of the README.  Thanks for the catch! b9c56857f67509b00509036f732befe3e9abf73f

**Comment by RichardLitt** [comment]
> quail.load_example_data now has a docstring and is documented on readthedocs. 

I am unable to find this. What am I missing? Thanks!

**Comment by andrewheusser** [comment]
Sorry about that!  It worked locally, but the build failed on readthedocs.  Working now!

http://cdl-quail.readthedocs.io/en/latest/quail.load_example_data.html#quail.load_example_data
