### ISSUE TITLE
documentation: Outline key intended users

### ISSUE THREAD

**Issue by RichardLitt** [ContextLab/quail#79]
I would like to know _who_ this repository is made for. Right now, there are no intended users specified in the README or in the paper.md that I can tell. Can you please add a small description of the intended user? 

Part of https://github.com/openjournals/joss-reviews/issues/424.

**Comment by andrewheusser** [comment]
@RichardLitt I've added a sentence in the README describing the intended user:

_The intended user of this toolbox is a memory researcher who seeks an easy way to analyze and visualize data from free recall psychology experiments._

see: 506283eaf126932515b5da12eee7dd8661269d81

**Comment by RichardLitt** [comment]
Thanks. Could you add it to paper/paper.md too?

**Comment by andrewheusser** [comment]
Sure! Done on f0fc4b81790f35953a99450ff20eedfffe0fde4d
