### ISSUE TITLE
JOSS: Add DOIs to all references which could have them

### ISSUE THREAD

**Issue by RichardLitt** [ContextLab/quail#80]
For instance, `@Hoga75`'s "Interitem encoding and directed search in free recall" should have one https://www.ncbi.nlm.nih.gov/pubmed/21287060 (10.3758/BF03212898). 

Please double check the others and add where relevant. 

Part of https://github.com/openjournals/joss-reviews/issues/424.

**Comment by andrewheusser** [comment]
@RichardLitt,  I added a DOI for the `@Hoga75` reference and checked the rest but they do not have one.

see: 183e922f5bef3dbfd450e65342fd98c55cc72b98
