### ISSUE TITLE
Can not import itertools in Python 3

### ISSUE THREAD

**Issue by EmilyWhitaker** [ContextLab/quail#99]
having trouble importing itertools in python 3 
When importing quail receives key error: 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8594c55e99e8> in <module>()
----> 1 import quail
      2 import seaborn as sns
      3 import pandas as pd
      4 import matplotlib.pyplot as plt
      5 import pickle

~/Desktop/quail/quail/__init__.py in <module>()
----> 1 from .load import load, load_example_data
      2 from .egg import Egg
      3 from .analysis import analyze
      4 from .plot import plot
      5 from .helpers import stack_eggs, crack_egg, recmat2egg, load_egg

~/Desktop/quail/quail/load.py in <module>()
      5 import re
      6 import csv
----> 7 from itertools import izip_longest
      8 from collections import Counter
      9 import pandas as pd

ImportError: cannot import name 'izip_longest'

**Comment by paxtonfitzpatrick** [comment]
Looks like this might have the answer:
https://stackoverflow.com/questions/38634810/failing-to-import-itertools-in-python-3-5-2
